version: "3.8"

services:
  redis:
    image: "redis:latest"
    container_name: "redis_container"
    restart: always
    volumes:
      - ./data:/data
    ports:
      - "6379:6379"
    command: ["redis-server", "--save", "60", "1", "--loglevel", "warning"]
    user: "1000:1000"  

  flask_app:
    build: .
    container_name: "iss_tracker"
    restart: always
    depends_on:
      - redis
    ports:
      - "5000:5000"
